export const GET_ERRORS = 'GET_ERRORS';
export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECT = 'GET_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';

//Types for BACKLOG ACTIONS

export const GET_BACKLOG_PROJECT_TASK = 'GET_BACKLOG_PROJECT_TASK';
export const GET_BACKLOG_AUTOMATION_TASK =
  'GET_BACKLOG_AUTOMATION_TASK';

export const GET_PROJECT_TASK = 'GET_PROJECT_TASK';
export const DELETE_PROJECT_TASK = 'DELETE_PROJECT_TASK';

export const GET_AUTOMATION_TASK = 'GET_AUTOMATION_TASK';
export const DELETE_AUTOMATION_TASK = 'DELETE_AUTOMATION_TASK';
export const DISPUTE_AUTOMATION_TASK = 'DISPUTE_AUTOMATION_TASK';
export const DISPUTE_ALL_TASKS = 'DISPUTE_ALL_TASKS';
export const GET_AUTOMATION_ALL_OPERATIONS =
  'GET_AUTOMATION_ALL_OPERATIONS';
export const GET_AUTOMATION_BY_OPERATIONS =
  'GET_AUTOMATION_BY_OPERATIONS';
export const UPDATE_STATUS_RSOCKET = 'UPDATE_STATUS_RSOCKET';
export const CHANGE_QUOTE = 'CHANGE_QUOTE';

export const GET_LAST_REQUESTS_BY_OPERATIONS =
  'GET_LAST_REQUESTS_BY_OPERATIONS';
export const GET_LAST_RESPONSES_BY_OPERATIONS =
  'GET_LAST_RESPONSES_BY_OPERATIONS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

//Types for PROFILE ACTIONS
export const GET_PROFILES = 'GET_PROFILES';
export const GET_PROFILE = 'GET_PROFILE';
export const DELETE_PROFILE = 'DELETE_PROFILE';

//Types for PROFILE BACKLOG ACTIONS
export const GET_PROFILE_BACKLOG = 'GET_PROFILE_BACKLOG';
export const GET_PROFILE_TASK = 'GET_PROFILE_TASK';
export const DELETE_PROFILE_TASK = 'DELETE_PROFILE_TASK';

//Task Types to Reder
export const TASK_TYPE_SKILSS = 'skill';
export const TASK_TYPE_EDUC = 'educ';
export const TASK_TYPE_LANG = 'lang';
export const TASK_TYPE_CLI_PRJ = 'cliPrj';

// Setting Direct Redux

export const SET_PROFILE_STAGED = 'SET_PROFILE_STAGED';
